name: reflectable
version: 4.0.13
description: >
  Reflection support based on code generation, using 'capabilities' to
  specify which operations to support, on which objects.
homepage: https://github.com/google/reflectable.dart
environment:
  sdk: '>=3.7.2 <4.0.0'
dependencies:
  analyzer:
  build:
  build_resolvers:
  build_config:
  build_runner:
  build_runner_core:
  dart_style:
  glob:
  logging:
  package_config:
  path:
  pub_semver:
  source_span:
dev_dependencies:
  build_test:
  lints:
  test:
